# Generated by Django 4.2.3 on 2023-07-23 10:52

import TeacherAdmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INSNAME', models.CharField(max_length=250)),
                ('FULLMARKS', models.IntegerField()),
                ('PASSMARKS', models.IntegerField()),
                ('FILENAME', models.FileField(default=None, max_length=250, null=True, upload_to='WordFiles')),
                ('ADDTEXT', models.CharField(max_length=500)),
                ('IMAGES_DICT', models.JSONField(default=TeacherAdmin.models.default_images_dict)),
            ],
        ),
    ]
