# Generated by Django 4.2.3 on 2023-07-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='IMAGES_DICT',
            field=models.JSONField(default={}),
        ),
    ]
