# Generated by Django 4.2.3 on 2023-07-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherAdmin', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='FOR_CLASS',
            field=models.IntegerField(default=0),
        ),
    ]
