# Generated by Django 4.2.3 on 2023-07-22 10:19

import TeacherAdmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherAdmin', '0002_admininfo_images_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='IMAGES_DICT',
            field=models.JSONField(default=TeacherAdmin.models.default_images_dict),
        ),
    ]
