# Generated by Django 4.2.3 on 2023-07-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherAdmin', '0003_admininfo_for_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='End_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='Start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
