# Generated by Django 4.2.3 on 2023-07-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherAdmin', '0005_alter_admininfo_end_time_alter_admininfo_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='End_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='Start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
