# Generated by Django 4.2.3 on 2023-08-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherAdmin', '0006_alter_admininfo_end_time_alter_admininfo_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='fetching_index',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
