# Generated by Django 4.2.3 on 2023-08-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherAdmin', '0007_admininfo_fetching_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininfo',
            name='fetching_index',
        ),
    ]
