# Generated by Django 4.2.3 on 2023-07-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank. Please provide Institution code.', 'invalid': 'Please enter a valid value for this field.', 'unique': 'Provided code is already in use. Try new one'}, max_length=50, unique=True),
        ),
    ]
