# Generated by Django 4.2.3 on 2023-08-02 15:05

from django.db import migrations, models
import validator.models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0003_customuser_active_portals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active_portals',
            field=models.JSONField(default=validator.models.default_portals_dict, null=True),
        ),
    ]
