# Generated by Django 4.2.3 on 2023-07-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StInfoModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Stream', models.IntegerField(choices=[(1, 'Science'), (2, 'Management')])),
                ('AdInsCode', models.CharField(max_length=10)),
                ('MarksAch', models.IntegerField(default=0, null=True)),
                ('Touched_Status', models.BooleanField(default=False)),
            ],
        ),
    ]
