# Generated by Django 4.2.3 on 2023-07-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stinfomodels',
            name='MarksAch',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stinfomodels',
            name='Stream',
            field=models.IntegerField(choices=[(1, 'Science'), (2, 'Management')]),
        ),
    ]
